import type { CSSProperties } from "react";

export const routexDarkThemeVars: CSSProperties = {
  ["--background" as string]: "0 0% 4%",
  ["--foreground" as string]: "0 0% 96%",
  ["--card" as string]: "0 0% 7%",
  ["--card-foreground" as string]: "0 0% 96%",
  ["--popover" as string]: "0 0% 7%",
  ["--popover-foreground" as string]: "0 0% 96%",
  ["--primary" as string]: "0 0% 96%",
  ["--primary-foreground" as string]: "0 0% 6%",
  ["--secondary" as string]: "0 0% 12%",
  ["--secondary-foreground" as string]: "0 0% 96%",
  ["--muted" as string]: "0 0% 11%",
  ["--muted-foreground" as string]: "0 0% 60%",
  ["--accent" as string]: "0 0% 14%",
  ["--accent-foreground" as string]: "0 0% 96%",
  ["--border" as string]: "0 0% 16%",
  ["--input" as string]: "0 0% 16%",
  ["--ring" as string]: "0 0% 83%",
  ["--sidebar-background" as string]: "0 0% 5%",
  ["--sidebar-foreground" as string]: "0 0% 95%",
  ["--sidebar-primary" as string]: "0 0% 95%",
  ["--sidebar-primary-foreground" as string]: "0 0% 5%",
  ["--sidebar-accent" as string]: "0 0% 12%",
  ["--sidebar-accent-foreground" as string]: "0 0% 95%",
  ["--sidebar-border" as string]: "0 0% 16%",
  ["--sidebar-ring" as string]: "0 0% 83%",
};
